language: python
jobs:
  include:
    - name: "docker"
      if: branch IN (master, dev)
      services: docker
      python: 3.6
      before_install:
        - docker --version
      install: 
        - pip install -U pip
        - pip install tox-travis
      script: tox -e docker
      after_success:
        -
    - name: "make"
      if: branch IN (master, dev)
      python: 3.6
      before_install:
        - make help
      addons:
        apt:
          update: true
      install: 
        - pip install -U pip
      script:
        - make all
        - source venv/bin/activate; pytest tests
      after_success:
        -
    - name: "Python 3.5"
      python: 3.5
      env: TOX_PYTHON_ENV=py35
    - name: "Python 3.6"
      python: 3.6
      env: TOX_PYTHON_ENV=py36
    - name: "Python 3.7"
      python: 3.7
      env: TOX_PYTHON_ENV=py37
before_install:
  - ls -la
install:
  - pip install -U pip
  - pip install tox-travis
  - pip install codecov
script:
  - tox -e $TOX_PYTHON_ENV -e lint
after_success:
  - codecov # submit coverage to https://codecov.io/gh/sertansenturk/tomato/
